### ISSUE TITLE
Support for renaming, removing enum values

### ISSUE THREAD

**Issue by mockdeep** [alassek/activerecord-pg_enum#10]
Thanks for this gem! It would be nice if this gem had support for renaming and removing enum values as well. It's rare for me to get things right the first time, so being able to easily change them later is pretty valuable.

It looks like on Postgres 10 and up renaming a value is [relatively painless](https://stackoverflow.com/a/45444822/372479). Removing a value isn't directly supported, but it looks like there is a workaround that [isn't too horrendous](https://stackoverflow.com/a/47305844/372479).

**Comment by alassek** [comment]
Hi @mockdeep, thanks for the feedback. Sorry it took so long for me to respond, I was on vacation.

I've just release `v1.1.0`, which adds `rename_enum` and `rename_enum_value`.

As for removing values, I've provided the necessary tools to do it but I'm not going to support data-munging directly. I don't want to be responsible for altering other people's business data.
