### ISSUE TITLE
Cannot add new enum value

### ISSUE THREAD

**Issue by DavidBuyCo** [alassek/activerecord-pg_enum#20]
Hi, thanks for your work!

I try to add a new enum value on an existing enum like the documentation
```ruby
class AddNewValue < ActiveRecord::Migration[5.1]
  def change
    add_enum_value :my_test_enum, 'FOO', before: 'BAR'
  end
end
```

But when i run migrations, i got this error
```shell
Caused by:
ActiveRecord::StatementInvalid: PG::ActiveSqlTransaction: ERROR:  ALTER TYPE ... ADD cannot run inside a transaction block
: ALTER TYPE my_test_enum ADD VALUE 'FOO' BEFORE 'BAR'
```

I use this gem on a rails 5.1 application

**Comment by alassek** [comment]
Hi! The error message is telling you whats wrong. Here's the important bit: `cannot run inside a transaction block`

It may not be obvious if you're not familiar with Rails migrations. Every migration runs inside a DB transaction by default. Sometimes that's invalid, like when you're building a concurrent index or in this case altering an enum.

Here's the relevant [documentation from PostgreSQL](https://www.postgresql.org/docs/9.1/sql-altertype.html):
> ALTER TYPE ... ADD VALUE (the form that adds a new value to an enum type) cannot be executed inside a transaction block.

Here's what you should do:
```ruby
class AddNewValue < ActiveRecord::Migration[5.1]
  disable_ddl_transaction!

  def change
    add_enum_value :my_test_enum, 'FOO', before: 'BAR'
  end
end
```

I'll update the documentation to make this more clear.

**Comment by DavidBuyCo** [comment]
Nice, it work! thank for your answer!
