### ISSUE TITLE
Support Rails enum options

### ISSUE THREAD

**Issue by AndrewSpeed** [alassek/activerecord-pg_enum#5]
👋 I ran into another use case which `activerecord-pg_enum` doesn't seem to support yet, and wanted to start a discussion about whether we would want to support it, and if so how it would be implemented.

As with #3, I'm happy to attempt implementing this change, if it's decided that we want to support it.

## Example
When using `activerecord-pg_enum`, we can't specify any of the options supported by the `ActiveRecord::Enum` class, e.g. `prefix` and `suffix`.

This means that two enums with the same keys will collide when it comes to the autogenerated methods provided by this class, for example:

### Rails enum
```ruby
class Conversation < ActiveRecord::Base
  enum status: [:active, :archived], _suffix: true
  enum comments_status: [:active, :inactive], _prefix: :comments
end
```

```ruby
conversation.active_status!
conversation.archived_status? # => false

conversation.comments_inactive!
conversation.comments_active? # => false
```

### Proposed activerecord-pg_enum implementation

One option to implement this behaviour could be to accept any options to the `include` and [pass them through to the `ActiveRecord::Enum` in the module definition](https://github.com/alassek/activerecord-pg_enum/blob/master/lib/active_record/pg_enum.rb#L81-L87)
```ruby
class Conversation < ActiveRecord::Base
  include PGEnum(status: [:active, :archived], _suffix: true)
  include PGEnum(status: [:active, :archived], _prefix: :comments)
end
```

```ruby
conversation.active_status!
conversation.archived_status? # => false

conversation.comments_inactive!
conversation.comments_active? # => false
```

**Comment by AndrewSpeed** [comment]
It turns out the gem does support this behaviour :man_facepalming: 

I've added a PR containing a test covering this functionality and updated the README with an example

**Comment by alassek** [comment]
@AndrewSpeed Sorry for the slow responses 😕 My GitHub notifications are so noisy it's hard to see anything.

**Comment by AndrewSpeed** [comment]
No problem at all @alassek, mine are _exactly_ the same way 😄 

Thanks for merging the PR 🎉
