### ISSUE TITLE
enum helper not working with change_table

### ISSUE THREAD

**Issue by alassek** [alassek/activerecord-pg_enum#7]
I assumed that `create_table` and `change_table` use the same class but it appears not.

```
NoMethodError: undefined method `enum' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::Table:0x00007fe990c40bb8>
```

**Comment by TylerRick** [comment]
I ran into this too. What's the workaround?

**Comment by TylerRick** [comment]
Based on https://github.com/alassek/activerecord-pg_enum/blob/master/lib/active_record/pg_enum/4.2/table_definition.rb (I'm using Rails 5.2), I tried adding this to the top of my migration and it ran without errors:
```ruby
ActiveRecord::ConnectionAdapters::PostgreSQL::Table.include ActiveRecord::PGEnum::TableDefinition
```

**Comment by alassek** [comment]
Use add_column for now
